"""Emit the TinyTapeout digital-tier tile from the compiler.

The digital tile is the fully digital emission target: the mask-programmed
array macro read by clocked bitline sampling, with the ternary MAC in
standard cells. The controller (rtl/tt_digital/cirom_dig_ctrl.sv) is a
shape-parameterized library primitive; this module emits the two
model/shape-specific files around it:

  * the tile top (TT pin contract, controller + front-end instantiation)
  * the front-end binding, tying the generic front-end interface to the
    named, mask-programmed array macro for the chosen weight matrix

For simulation the macro module is provided behaviorally
(rtl/chip/sim/macro_array_beh.sv with ANKHDJET_ARRAY_MODULE set to the
same macro name); for hardening it is the macro's blackbox netlist and
GDS. The weights therefore enter the tile exactly as they enter every
other vehicle: as the macro's programming layer, never as RTL constants.
"""

from __future__ import annotations

from pathlib import Path


def emit_tt_digital_top(
    top_name: str = "tt_um_darga_cirom",
    n_rows: int = 64,
    n_cols: int = 32,
    n_acc: int = 8,
    acc_w: int = 12,
    act_w: int = 4,
    store_acts: int = 1,
) -> str:
    """Emit the TT top: pin contract wrapping the controller and front end.

    store_acts=0 emits the streamed-activation variant (no on-die store;
    the host supplies one activation byte per row pair, re-sent each
    pass), trading at-speed MVM for the store's area and wiring.
    """
    act_note = ("on-die activation store" if store_acts
                else "host-streamed activations (no on-die store)")
    return f"""// GENERATED by ankhdjet.backend.tt_digital -- do not edit.
// TinyTapeout digital-tier tile: mask-programmed CiROM array, clocked
// digital bitline sampling, on-die ternary MAC ({n_cols} cols x {acc_w}-bit,
// {n_acc} accumulators muxed across {n_cols // n_acc} pass(es)), {act_note}.
`default_nettype none

module {top_name} (
`ifdef USE_POWER_PINS
    inout  wire       VGND,
    inout  wire       VDPWR,
`endif
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    wire [{n_rows - 1}:0] wl;
    wire                  pre_n;
    wire [{n_cols - 1}:0] blp, bln;
    wire                  result_valid, busy, done;

    wire _unused = &{{ena, uio_in[7:5], 1'b0}};

    cirom_dig_ctrl #(
        .N_ROWS({n_rows}), .N_COLS({n_cols}),
        .N_ACC({n_acc}), .ACC_W({acc_w}), .ACT_W({act_w}),
        .STORE_ACTS({store_acts})
    ) u_ctrl (
        .clk(clk), .rst_n(rst_n),
        .ui(ui_in),
        .act_wr(uio_in[0]),
        .start(uio_in[1]),
        .mode(uio_in[2]),
        .cfg_mode(uio_in[3]),
        .cfg_in(uio_in[4]),
        .wl(wl), .pre_n(pre_n),
        .blp(blp), .bln(bln),
        .result(uo_out),
        .result_valid(result_valid),
        .busy(busy),
        .done(done)
    );

    cirom_dig_afe #(
        .N_ROWS({n_rows}), .N_COLS({n_cols})
    ) u_afe (
`ifdef USE_POWER_PINS
        .VPWR(VDPWR), .VGND(VGND),
`endif
        .wl(wl), .pre_n(pre_n),
        .blp(blp), .bln(bln)
    );

    assign uio_out = {{done, busy, result_valid, 5'b0}};
    assign uio_oe  = 8'b1110_0000;

endmodule

`default_nettype wire
"""


def emit_tt_digital_afe(
    macro_module: str,
    n_rows: int = 64,
    n_cols: int = 32,
    macro_bls: int = 32,
) -> str:
    """Emit the front-end binding to a named mask-programmed array macro."""
    wl_ports = ",\n        ".join(
        ", ".join(f".WL_{r}(wl[{r}])" for r in range(g, g + 8))
        for g in range(0, n_rows, 8)
    )
    blp_ports = ", ".join(f".BLP_{c}(blp_all[{c}])" for c in range(macro_bls))
    bln_ports = ", ".join(f".BLN_{c}(bln_all[{c}])" for c in range(macro_bls))
    return f"""// GENERATED by ankhdjet.backend.tt_digital -- do not edit.
// Front-end binding: the generic digital front-end interface tied to the
// mask-programmed array macro `{macro_module}`. The weight matrix lives in
// that macro's programming layer; recompiling a model regenerates the
// macro's mask program, never this RTL.
`default_nettype none

module cirom_dig_afe #(
    parameter int N_ROWS = {n_rows},
    parameter int N_COLS = {n_cols}
)(
`ifdef USE_POWER_PINS
    inout  wire              VPWR,
    inout  wire              VGND,
`endif
    input  wire [N_ROWS-1:0] wl,
    input  wire              pre_n,
    output wire [N_COLS-1:0] blp,
    output wire [N_COLS-1:0] bln
);
    wire [{macro_bls - 1}:0] blp_all, bln_all;

    // Power ports connect only in powered views; otherwise they are left
    // dangling so the physical flow's global connections can bind them to
    // the tile power nets (a tie-off would block that binding).
    {macro_module} u_macro (
        .PRE_N(pre_n),
        {wl_ports},
        {blp_ports},
        {bln_ports}
`ifdef USE_POWER_PINS
        , .VPWR(VPWR), .VGND(VGND)
`endif
    );

    assign blp = blp_all[N_COLS-1:0];
    assign bln = bln_all[N_COLS-1:0];
endmodule

`default_nettype wire
"""


def emit_tt_digital(
    out_dir: Path | str,
    weights: str = "checker",
    top_name: str = "tt_um_darga_cirom",
    n_rows: int = 64,
    n_cols: int = 32,
    n_acc: int = 8,
    acc_w: int = 12,
    act_w: int = 4,
    store_acts: int = 1,
    macro_cols: int = 32,
    weights_matrix=None,
) -> dict:
    """Emit both tile files for a named weight matrix; return their paths.

    `macro_cols` is the array macro's weight-column count (its BLP/BLN
    pair count); `n_cols` is how many of those columns the tile senses
    and accumulates, up to all of them.

    When `weights_matrix` (an (n_rows, macro_cols) ternary array) is
    given, the macro's mask program is emitted too, as
    `<out_dir>/<weights>.wmat` in the array generators' format: the
    compiled tile and its programming layer then come from the same call.
    """
    if n_cols > macro_cols:
        raise ValueError(f"n_cols {n_cols} exceeds macro_cols {macro_cols}")
    macro_module = f"macro_array_pc_{n_rows}x{macro_cols}_{weights}"
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    top = out / f"{top_name}.sv"
    afe = out / "cirom_dig_afe_bind.sv"
    top.write_text(emit_tt_digital_top(
        top_name=top_name, n_rows=n_rows, n_cols=n_cols,
        n_acc=n_acc, acc_w=acc_w, act_w=act_w, store_acts=store_acts))
    afe.write_text(emit_tt_digital_afe(
        macro_module=macro_module, n_rows=n_rows, n_cols=n_cols,
        macro_bls=macro_cols))
    result = {"top": top, "afe": afe, "macro_module": macro_module}
    if weights_matrix is not None:
        import numpy as np
        from ankhdjet.backend.wmat import emit_wmat
        W = np.asarray(weights_matrix)
        want = (n_rows, macro_cols)
        if W.shape != want:
            raise ValueError(
                f"weights_matrix shape {W.shape} != macro shape {want}")
        result["wmat"] = emit_wmat(W, out / f"{weights}.wmat")
    return result
