#!/usr/bin/env bash
# Export the Darga TinyTapeout submission into the darga-tt repo (a fork of
# the TT template). The Azara repo is the SINGLE SOURCE OF TRUTH -- darga-tt
# is generated by this script, never hand-maintained, so it cannot drift.
# Populates:
#   src/project.v     : blackbox GENERATED from the compiler-emitted top
#                       (tt_um_darga_cirom, the hardened parameterization:
#                       weights=test0, n_cols=32, n_acc=4, store_acts=0) so
#                       the submission stub tracks the emission automatically.
#   info.yaml         : copied from tt_digital/info.yaml (canonical metadata).
#   docs/info.md      : copied from tt_digital/info.md (canonical datasheet).
#   gds/, lef/        : copied from the latest hardened librelane/tt_digital
#                       run, when one exists (skipped otherwise).
#
# Usage: bash tt_digital/gen_submission.sh [path-to-darga-tt]   (default: ../darga-tt)
set -u
REPO=$(cd "$(dirname "$0")/.." && pwd)
TT=${1:-$(cd "$REPO/.." && pwd)/darga-tt}
TOP=tt_um_darga_cirom
SRCDIR=librelane/tt_digital/build/src
[ -d "$TT/.git" ] || { echo "ERROR: '$TT' is not the darga-tt repo (fork the TT template there)"; exit 1; }

echo "== emit the tile (hardened parameterization) =="
uv run --project "$REPO" python - <<EOF || exit 1
from ankhdjet.backend.tt_digital import emit_tt_digital
r = emit_tt_digital("$REPO/$SRCDIR", weights="test0", n_cols=32, n_acc=4, store_acts=0)
print(f"   -> {r['top']} (macro {r['macro_module']})")
EOF

echo "== generate src/project.v from the emitted $TOP.sv =="
mkdir -p "$TT/src"
tmp=$(mktemp)
{
  echo "// GENERATED by tt_digital/gen_submission.sh from the compiler-emitted $TOP.sv -- DO NOT EDIT."
  echo "// Blackbox for Darga, the CiROM digital-tier tile: the hardened"
  echo "// gds/$TOP.gds + lef/$TOP.lef implement it. Fully digital: no analog pins."
  echo "\`default_nettype none"
  echo ""
  verilator -E -DUSE_POWER_PINS "$REPO/$SRCDIR/$TOP.sv" 2>/dev/null \
    | grep -vE "^\`line|^\`begin_keywords|^\`end_keywords" \
    | awk -v top="$TOP" '
        /^module /&&$0 ~ top {p=1}
        p { sub(/[[:space:]]+$/,""); if ($0!="") print }
        p&&/\);[[:space:]]*$/ { print "    // Blackbox: implemented by the hardened GDS."; print "endmodule"; exit }'
  echo "\`default_nettype wire"
} > "$tmp"
grep -q "^endmodule" "$tmp" || { echo "ERROR: generation failed (no endmodule) -- check verilator/awk"; rm -f "$tmp"; exit 1; }
mv "$tmp" "$TT/src/project.v"
echo "   -> $TT/src/project.v ($(grep -cE 'input|output|inout' "$TT/src/project.v") ports)"

echo "== verify src/project.v interface == emitted $TOP.sv =="
vd=$(mktemp -d)
yosys -q -p "read_verilog -sv $TT/src/project.v; write_json $vd/proj.json" 2>/dev/null \
  || { echo "ERROR: generated project.v does not parse"; rm -rf "$vd"; exit 1; }
yosys -q -p "read_verilog -sv -DUSE_POWER_PINS $REPO/$SRCDIR/$TOP.sv; write_json $vd/real.json" 2>/dev/null \
  || { echo "ERROR: could not read $SRCDIR/$TOP.sv"; rm -rf "$vd"; exit 1; }
uv run --project "$REPO" python - "$vd/proj.json" "$vd/real.json" "$TOP" <<'PY'
import json, sys
def info(f, top):
    m = json.load(open(f))['modules'][top]
    return {k: (v['direction'], len(v['bits'])) for k, v in m['ports'].items()}, len(m.get('cells', {}))
p, pc = info(sys.argv[1], sys.argv[3]); r, _ = info(sys.argv[2], sys.argv[3])
bad = [k for k in sorted(set(p) | set(r)) if p.get(k) != r.get(k)]
if bad:
    print("   MISMATCH:", *[f"{k}(proj={p.get(k)},top={r.get(k)})" for k in bad]); sys.exit(1)
if pc:
    print(f"   NOT A BLACKBOX ({pc} cells)"); sys.exit(1)
print(f"   OK: {len(p)} ports match tt_um, blackbox clean")
PY
vrc=$?; rm -rf "$vd"
[ $vrc -eq 0 ] || { echo "ERROR: project.v interface check failed -- fix the emitter or the generator"; exit 1; }

echo "== copy canonical metadata =="
cp "$REPO/tt_digital/info.yaml" "$TT/info.yaml"
mkdir -p "$TT/docs"; cp "$REPO/tt_digital/info.md" "$TT/docs/info.md"
echo "   -> info.yaml, docs/info.md"

echo "== copy hardened GDS/LEF (latest librelane/tt_digital run) =="
RUN=$(ls -dt "$REPO"/librelane/tt_digital/runs/*/final 2>/dev/null | head -1)
GDS=$(find "$RUN" -name "$TOP.gds" 2>/dev/null | head -1)
LEF=$(find "$RUN" -name "$TOP.lef" 2>/dev/null | head -1)
if [ -n "${GDS:-}" ] && [ -n "${LEF:-}" ]; then
  mkdir -p "$TT/gds" "$TT/lef"; cp "$GDS" "$TT/gds/$TOP.gds"; cp "$LEF" "$TT/lef/$TOP.lef"
  echo "   -> gds/$TOP.gds + lef/$TOP.lef (from ${RUN#$REPO/})"
  echo "== normalize the shipped LEF (template-exact pin rects + power pins) =="
  uv run --project "$REPO" python "$REPO/librelane/tt_analog/fix_submission_lef.py" \
    "$TT/lef/$TOP.lef" "$REPO/librelane/tt_digital/tt_digital_1x2.def" || { echo "ERROR: LEF fix failed"; exit 1; }
  cp "$TT/src/project.v" "$TT/gds/$TOP.v"   # precheck reads <gds-stem>.v
  echo "== finish the shipped GDS (power labels/pins, met5 strip) + verify =="
  klayout -b -r "$REPO/librelane/tt_digital/finish_gds.py" -rd gds="$TT/gds/$TOP.gds" \
    | grep -E "painted|labeled|removed" || { echo "ERROR: GDS finishing failed"; exit 1; }
  # Differential DRC gate: the finished GDS must add ZERO items over the
  # signoff GDS under the same deck and the same local klayout. Absolute
  # counts drift with the klayout engine version (the same signoff GDS can
  # report items under a newer engine than the recorded 0); the engine of
  # record is the TT precheck's pinned klayout, so the local gate only
  # asserts what finishing is responsible for: no new items.
  DECK=$(find "${PDK_ROOT:-$HOME/.ciel}" "$HOME/.ciel" "$HOME/.volare" -name "sky130A_mr.drc" 2>/dev/null | head -1)
  if [ -n "$DECK" ]; then
    RPT_PRE=$(mktemp -u).lyrdb; RPT_POST=$(mktemp -u).lyrdb
    for pair in "$GDS:$RPT_PRE" "$TT/gds/$TOP.gds:$RPT_POST"; do
      klayout -b -r "$DECK" -rd input="${pair%%:*}" -rd topcell="$TOP" -rd report="${pair#*:}" \
        -rd feol=true -rd beol=true -rd offgrid=true -rd seal=false -rd threads=16 >/dev/null 2>&1
    done
    uv run --project "$REPO" python - "$RPT_PRE" "$RPT_POST" <<'PY'
import re, sys
def items(f):
    out = set()
    for it in re.findall(r"<item>.*?</item>", open(f).read(), re.S):
        cat = re.search(r"<category>'([^']*)'</category>", it)
        val = re.search(r"<value>([^<]*)</value>", it)
        out.add((cat.group(1) if cat else "?", val.group(1) if val else ""))
    return out
pre, post = items(sys.argv[1]), items(sys.argv[2])
new = post - pre
print(f"   signoff GDS: {len(pre)} items, shipped GDS: {len(post)} items under the local engine")
if new:
    for c, v in sorted(new): print(f"   NEW: {c} {v[:70]}")
    sys.exit(1)
print("   OK: finishing added no DRC items (TT precheck's pinned engine is the absolute gate)")
PY
    drc_rc=$?
    rm -f "$RPT_PRE" "$RPT_POST"
    [ $drc_rc -eq 0 ] || { echo "ERROR: GDS finishing introduced new DRC items"; exit 1; }
  else
    echo "   -- deck not found; skipped DRC verify"
  fi
else
  echo "   -- SKIPPED: no hardened GDS yet (harden via librelane/tt_digital, then re-run)"
fi
echo "done. review + commit in $TT, then push to your TinyTapeout fork."
