#!/usr/bin/env bash
# Array-size-agnostic OpenROAD wrapper. Synthesizes the wrapper RTL
# generated by gen_anchor_abstracts.py and runs floorplan + place + STA on the
# resulting design with the cirom_array hard macro placed as a fixed
# block. Works for any (rows, cols, pdk, biroma) combination.
#
# Usage:
#   run_openroad.sh <rows> <cols>                  # SKY130 (default)
#   run_openroad.sh <rows> <cols> --pdk gf180
#   run_openroad.sh <rows> <cols> --biroma
#   run_openroad.sh <rows> <cols> --pdk gf180 --biroma

set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"

ROWS="${1:?rows required}"
COLS="${2:?cols required}"
shift 2
PDK="sky130"
BIROMA=""
while [ $# -gt 0 ]; do
    case "$1" in
        --pdk) PDK="$2"; shift 2;;
        --biroma) BIROMA="--biroma"; shift;;
        *) echo "unknown arg: $1" >&2; exit 2;;
    esac
done

# Build the macro abstraction.
uv run --project "$REPO" python "$HERE/gen_anchor_abstracts.py" "$ROWS" "$COLS" --pdk "$PDK" $BIROMA

# Compute the file_stem the generator used.
SUFFIX="_${PDK}"

[ -n "$BIROMA" ]       && SUFFIX="${SUFFIX}_biroma"
STEM="cirom_array_${ROWS}x${COLS}${SUFFIX}"
NAME="cirom_array_${ROWS}x${COLS}"
# The synth/wrapper files are PDK-aware but BiROMA-agnostic (BiROMA only
# changes the macro abstraction's area accounting; the wrapper RTL is
# identical). So the synth-stem omits the _biroma suffix even when the
# macro stem includes it.
SYNTH_SUFFIX="_${PDK}"

SYNTH_STEM="cirom_array_${ROWS}x${COLS}${SYNTH_SUFFIX}"

OUT="$REPO/build/${STEM}_openroad"
mkdir -p "$OUT"

# Per-PDK constants threaded into the OpenROAD TCL via env.
case "$PDK" in
    sky130)
        TECH_LEF="/host/.volare/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef"
        SC_LEF="/host/.volare/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef"
        SC_LIB="/host/.volare/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib"
        SITE="unithd"
        LAYER_HOR="met3"
        LAYER_VER="met2"
        CLK_NS="5.0"
        TRACK_LAYERS="li1 0.23 0.46 0.17 0.34 met1 0.17 0.34 0.17 0.34 met2 0.23 0.46 0.23 0.46 met3 0.34 0.68 0.34 0.68 met4 0.46 0.92 0.46 0.92 met5 1.70 3.40 1.70 3.40"
        EXTRA_MOUNT=(-v "$HOME/.volare":/host/.volare)
        SETUP_LIB=""
        ;;
    gf180)
        # Tech LEF is sourced from the ORFS bundle (volare-installed
        # gf180mcuD ships only the standard-cell LEF, no tech LEF).
        TECH_LEF="/OpenROAD-flow-scripts/flow/platforms/gf180/lef/gf180mcu_5LM_1TM_9K_9t_tech.lef"
        SC_LEF="/host/.volare/gf180mcuD/libs.ref/gf180mcu_fd_sc_mcu9t5v0/lef/gf180mcu_fd_sc_mcu9t5v0.lef"
        SC_LIB="/host/.volare/gf180mcuD/libs.ref/gf180mcu_fd_sc_mcu9t5v0/lib/gf180mcu_fd_sc_mcu9t5v0__tt_025C_5v00.lib"
        SITE="GF018hv5v_green_sc9"
        LAYER_HOR="Metal3"
        LAYER_VER="Metal2"
        CLK_NS="7.0"
        TRACK_LAYERS="Metal1 0.28 0.56 0.28 0.56 Metal2 0.28 0.56 0.28 0.56 Metal3 0.28 0.56 0.28 0.56 Metal4 0.56 1.12 0.56 1.12 Metal5 1.12 2.24 1.12 2.24"
        EXTRA_MOUNT=(-v "$HOME/.volare":/host/.volare)
        SETUP_LIB=""
        ;;
    *) echo "unsupported PDK: $PDK" >&2; exit 2;;
esac

# Macro footprint from the freshly-emitted LEF — read SIZE and pad with
# a per-PDK margin sized for the standard-cell row height (sky130_hd's
# 2.72 um vs gf180's 5.04 um).
MACRO_LEF_HOST="$HERE/build/${STEM}.lef"
MACRO_W=$(awk '/^  SIZE / {printf "%d", $2 + 0.5}' "$MACRO_LEF_HOST")
MACRO_H=$(awk '/^  SIZE / {printf "%d", $4 + 0.5}' "$MACRO_LEF_HOST")
# Wrapper standard-cell area scales linearly with col count (each BL
# output bit needs a flop + datapath). Pad the die with margin
# proportional to that load on top of a per-PDK floor.
case "$PDK" in
    sky130) PAD_FLOOR=50;  PAD_PER_COL=2;  MACRO_OFF=20; CORE_MARGIN=10;;
    gf180)  PAD_FLOOR=120; PAD_PER_COL=5;  MACRO_OFF=40; CORE_MARGIN=20;;
esac
PAD_UM=$(( PAD_FLOOR + PAD_PER_COL * COLS ))
DIE_W=$(( MACRO_W + PAD_UM ))
DIE_H=$(( MACRO_H + PAD_UM ))
MACRO_X=$MACRO_OFF
MACRO_Y=$MACRO_OFF

mkdir -p "$REPO/build"

# Yosys runs inside container so the SC Liberty path resolves either way.
docker run --rm \
    -v "$REPO":/host/repo \
    "${EXTRA_MOUNT[@]}" \
    -w /host/repo \
    --user "$(id -u):$(id -g)" \
    openroad/orfs:latest \
    bash -c "${SETUP_LIB}source /OpenROAD-flow-scripts/env.sh && yosys /host/repo/macro/sky130/build/${SYNTH_STEM}_synth.ys > /host/repo/build/${STEM}_synth.log 2>&1"

docker run --rm \
    -v "$REPO":/host/repo \
    "${EXTRA_MOUNT[@]}" \
    -w /host/repo \
    --user "$(id -u):$(id -g)" \
    -e ANKHDJET_TECH_LEF="$TECH_LEF" \
    -e ANKHDJET_SC_LEF="$SC_LEF" \
    -e ANKHDJET_SC_LIB="$SC_LIB" \
    -e ANKHDJET_MACRO_LEF="/host/repo/macro/sky130/build/${STEM}.lef" \
    -e ANKHDJET_MACRO_LIB="/host/repo/macro/sky130/build/${STEM}.lib" \
    -e ANKHDJET_GATES_V="/host/repo/macro/sky130/build/${SYNTH_STEM}_test_harness.gates.v" \
    -e ANKHDJET_TOP="${NAME}_test_harness" \
    -e ANKHDJET_OUT_DIR="/host/repo/build/${STEM}_openroad" \
    -e ANKHDJET_DIE_AREA="0 0 $DIE_W $DIE_H" \
    -e ANKHDJET_CORE_MARGIN="$CORE_MARGIN" \
    -e ANKHDJET_SITE="$SITE" \
    -e ANKHDJET_LAYER_HOR="$LAYER_HOR" \
    -e ANKHDJET_LAYER_VER="$LAYER_VER" \
    -e ANKHDJET_CLK_PERIOD_NS="$CLK_NS" \
    -e ANKHDJET_MACRO_X="$MACRO_X" \
    -e ANKHDJET_MACRO_Y="$MACRO_Y" \
    -e ANKHDJET_TRACK_LAYERS="$TRACK_LAYERS" \
    openroad/orfs:latest \
    bash -c "${SETUP_LIB}source /OpenROAD-flow-scripts/env.sh && openroad -no_init -exit /host/repo/macro/sky130/run_openroad.tcl 2>&1 | tee /host/repo/build/${STEM}_openroad.log"
