// sa_band16 sense-amp band blackbox (auto-generated)

`celldefine
(* blackbox *)
module sa_band16 (
    input  STROBE,
    input  BLP_0,
    input  BLP_1,
    input  BLP_2,
    input  BLP_3,
    input  BLP_4,
    input  BLP_5,
    input  BLP_6,
    input  BLP_7,
    input  BLP_8,
    input  BLP_9,
    input  BLP_10,
    input  BLP_11,
    input  BLP_12,
    input  BLP_13,
    input  BLP_14,
    input  BLP_15,
    input  BLN_0,
    input  BLN_1,
    input  BLN_2,
    input  BLN_3,
    input  BLN_4,
    input  BLN_5,
    input  BLN_6,
    input  BLN_7,
    input  BLN_8,
    input  BLN_9,
    input  BLN_10,
    input  BLN_11,
    input  BLN_12,
    input  BLN_13,
    input  BLN_14,
    input  BLN_15,
    output OUTP_0,
    output OUTP_1,
    output OUTP_2,
    output OUTP_3,
    output OUTP_4,
    output OUTP_5,
    output OUTP_6,
    output OUTP_7,
    output OUTP_8,
    output OUTP_9,
    output OUTP_10,
    output OUTP_11,
    output OUTP_12,
    output OUTP_13,
    output OUTP_14,
    output OUTP_15,
    output OUTM_0,
    output OUTM_1,
    output OUTM_2,
    output OUTM_3,
    output OUTM_4,
    output OUTM_5,
    output OUTM_6,
    output OUTM_7,
    output OUTM_8,
    output OUTM_9,
    output OUTM_10,
    output OUTM_11,
    output OUTM_12,
    output OUTM_13,
    output OUTM_14,
    output OUTM_15,
    inout  VDD,
    inout  VGND
);
endmodule
`endcelldefine
