"""Author sa_se_band16.lib with device-derived pin capacitances.

The band exposes 16 sa_se comparators. Per-pin loads come from the
sa_se schematic device geometry (sky130 1.8V Cox ~= 8.3 fF/um^2):
  STROBE_i : tail nfet 14x1 + 2 reset pfets 0.84x1  ~= 130 fF
  BL_i     : input nfet 8x2                          ~= 135 fF
  VREF_i   : reference input nfet 8x2                ~= 135 fF
BL/VREF carry no max_transition: BL is the analog bitline ramp and
VREF is a DC reference -- slew checks are meaningless on both.

HIT max_capacitance = 60 fF is a hard functional bound, not a slew
nicety: the StrongARM races its two output nodes, and load imbalance
between HIT (routed) and HITB (internal, ~0 fF) biases the race.
Measured on the C-extracted macro at ss/100C/1.62V with 1 ns strobe
edges: correct decisions at 100 fF imbalance, the floating-victim
side FLIPS at 150 fF, everything flips at 200 fF (balanced loads are
fine to 250+). 60 fF keeps every routed HIT pin >2x under the cliff
by making the resizer buffer anything heavier.
"""
import os
from pathlib import Path

N = int(os.environ.get("ANKHDJET_BAND_N", "16"))
OUT = Path(__file__).resolve().parents[3] / f"macro/sky130/abstracts/sa_se_band{N}.lib"
OUT_BB = OUT.with_suffix("").with_suffix("")  # strip .lib
BB = Path(str(OUT)[:-4] + ".bb.v")

HEADER = """/* sa_se_band16 sense comparator Liberty (auto-generated by
 * cell/sky130/sense_se/author_band_lib.py -- device-derived pin caps).
 * Inputs: BL (sensed bit-line), VREF (~VDD/2 reference), STROBE.
 * Outputs: HIT (=BL<VREF, i.e. discharged).
 */
library (sa_se_band16) {
  technology (cmos);
  delay_model : table_lookup;
  time_unit                    : "1ns";
  voltage_unit                 : "1V";
  current_unit                 : "1mA";
  pulling_resistance_unit      : "1kohm";
  capacitive_load_unit (1, ff);
  leakage_power_unit           : "1nW";
  default_input_pin_cap        : 0.001;
  default_inout_pin_cap        : 0.001;
  default_output_pin_cap       : 0.000;
  nom_voltage                  : 1.80;
  nom_temperature              : 25.0;
  nom_process                  : 1.0;
  input_threshold_pct_rise     : 50;
  input_threshold_pct_fall     : 50;
  output_threshold_pct_rise    : 50;
  output_threshold_pct_fall    : 50;
  slew_lower_threshold_pct_rise: 20;
  slew_upper_threshold_pct_rise: 80;
  slew_lower_threshold_pct_fall: 20;
  slew_upper_threshold_pct_fall: 80;
  slew_derate_from_library     : 1.0;
  voltage_map (VDD, 1.80);
  voltage_map (VGND, 0.0);
  lu_table_template (sa_nldm_3x3) {
    variable_1 : input_net_transition;
    variable_2 : total_output_net_capacitance;
    index_1 ("0.05, 0.30, 0.75");
    index_2 ("5.0, 30.0, 60.0");
  }
  cell (sa_se_band16) {
    is_macro_cell : true;
    pg_pin (VDD)  { pg_type : primary_power;  voltage_name : VDD; }
    pg_pin (VGND) { pg_type : primary_ground; voltage_name : VGND; }
"""

def main():
    lines = [HEADER.replace("band16", f"band{N}")]
    for i in range(N):
        lines.append(f"    pin (STROBE_{i}) {{ direction : input; clock : true; capacitance : 130.0; max_transition : 0.75; }}\n")
        lines.append(f"    pin (BL_{i})   {{ direction : input; capacitance : 135.0; }}\n")
        lines.append(f"    pin (VREF_{i}) {{ direction : input; capacitance : 135.0; }}\n")
        # The regenerated latch output drives like a ~1.5 kohm source:
        # the arc lets the resizer model and buffer the HIT route (an
        # arc-less pin is invisible to repair_design).
        lines.append(
            f"    pin (HIT_{i})  {{ direction : output; capacitance : 0.0; max_capacitance : 60.0;\n"
            f"      timing () {{\n"
            f'        related_pin : "STROBE_{i}";\n'
            f"        timing_type : rising_edge;\n"
            f"        cell_rise (sa_nldm_3x3) {{\n"
            f'          values ("1.00, 1.04, 1.09", "1.05, 1.09, 1.14", "1.15, 1.19, 1.24");\n'
            f"        }}\n"
            f"        rise_transition (sa_nldm_3x3) {{\n"
            f'          values ("0.05, 0.15, 0.28", "0.06, 0.16, 0.29", "0.08, 0.18, 0.31");\n'
            f"        }}\n"
            f"        cell_fall (sa_nldm_3x3) {{\n"
            f'          values ("1.00, 1.04, 1.09", "1.05, 1.09, 1.14", "1.15, 1.19, 1.24");\n'
            f"        }}\n"
            f"        fall_transition (sa_nldm_3x3) {{\n"
            f'          values ("0.05, 0.15, 0.28", "0.06, 0.16, 0.29", "0.08, 0.18, 0.31");\n'
            f"        }}\n"
            f"      }}\n"
            f"    }}\n")
    lines.append("  }\n}\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}")

    # Verilog blackbox alongside the lib (the chip/tile netlist view)
    ports = ["  inout VDD", "  inout VGND"]
    for i in range(N):
        ports += [f"  input BL_{i}", f"  input VREF_{i}",
                  f"  input STROBE_{i}", f"  output HIT_{i}"]
    bb = ("`timescale 1ns/1ps\n(* blackbox *)\n"
          f"module sa_se_band{N} (\n" + ",\n".join(ports) +
          "\n);\nendmodule\n")
    BB.write_text(bb)
    print(f"wrote {BB}")

if __name__ == "__main__":
    main()
